server:
  port: 8082
  servlet:
    context-path: /BasicmodelService
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootbasic?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    #    schema:
    #      - classpath:department.sql
    #      - classpath:employee.sql
    #    initialization-mode: always
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  mapper‐locations: classpath:com/aaron/mapper/*.xml
  type-aliases-package: com.aaron.pojo.*
logging:
  config: classpath:logback.xml
  level:
    cn.jay.repository: trace

dubbo:
  application:
    name: basicmodel-serviceprovider
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages:
      - com.aaron.service
  protocol:
    name: dubbo
    port: 20880
